### ISSUE TITLE
Classifier '<config-value>' does not have a companion object, and thus must be initialized here

### ISSUE THREAD

**Issue by kewitschka** [zladovan/gradle-avrohugger-plugin#10]
I use Scala 2.12.18 and Gradle 8.7. If I want to configure anything I get the error
> Classifier '<config-value>' does not have a companion object, and thus must be initialized here

Example:  
`avrohugger {
    sourceFormat = SpecificRecord
}`

> Classifier 'SpecificRecord' does not have a companion object, and thus must be initialized here

Same with _typeMapping_ etc.

**Comment by zladovan** [comment]
Is it just complain of the IDE or is it build failing with this error ?

**Comment by kewitschka** [comment]
The build is failing.

**Comment by zladovan** [comment]
I am having success with following configuration with Gradle 8.7 and OpenJDK 11.0.23

```
plugins {
    id 'scala'
    id 'com.zlad.gradle.avrohugger' version '0.8.0'
}

repositories {
   mavenCentral()
}

dependencies {
    implementation 'org.scala-lang:scala-library:2.12.18'
    implementation 'org.apache.avro:avro:1.11.1'
}

avrohugger {
    sourceFormat = SpecificRecord
}
```

Do you see some difference ? Maybe java version ?

**Comment by kewitschka** [comment]
Thank you, it was the java version.

**Comment by zladovan** [comment]
btw. which java version was producing this error ?

**Comment by kewitschka** [comment]
The project where it failed used Java 21.
