### ISSUE TITLE
kotlin DSL

### ISSUE THREAD

**Issue by geoHeil** [zladovan/gradle-avrohugger-plugin#4]
How can this plugin be used with Gradle's new Kotlin DSL?

**Comment by zladovan** [comment]
Hi,

Unfortunately there is no explicit support for Kotlin DSL.

I tried to use it from Kotlin DSL only now for the first time.
It looks it is possible but it is not so easy to modify `typeMapping` and `sourceFormat`.

Here is the example:
```kotlin
import com.zlad.gradle.avrohugger.AvrohuggerExtension
import com.zlad.gradle.avrohugger.CustomTypes

plugins {
    id ("scala") 
    id ("com.zlad.gradle.avrohugger") version "0.4.4"
}

repositories {
   mavenCentral()
}

dependencies {
    implementation ("org.scala-lang:scala-library:2.12.10")
}

avrohugger {
    sourceDirectories.setFrom(files("src-avro"))
    
    destinationDirectory.set(file("src-scala"))
    
    namespaceMapping.set(mapOf(
        "example.idl" to "com.zlad"
    ))

    typeMapping.set({
        val types = CustomTypes()
        // I've got some complains by IDE for following two lines but build was fine
        types.protocolType = AvrohuggerExtension.ScalaADT
        types.enumType = AvrohuggerExtension.ScalaCaseObjectEnum
        // change another types here ...
        types
    }())

    sourceFormat.set(AvrohuggerExtension.Standard)
}
```

I will try to improve support for Kotlin DSL in next days.
Meanwhile you can try to use it as in the example above.

**Comment by geoHeil** [comment]
Great! Already looking forward to a better Kotlin DSL support.

**Comment by zladovan** [comment]
After deeper investigation I found out that there was nicer way to configure it.
I've added an example to README. 
See: https://github.com/zladovan/gradle-avrohugger-plugin#how-to-use-with-kotlin-dsl

Additionally I've fixed those complains in IDE around type mappings, use version `0.5.0` to get this fix.

I am still getting warning on `namespaceMapping.set` but I decided to accept it for now.
